# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  # Admin user settings:
  admin_name: Admin
  admin_email: admin@admin.com
  admin_password: admin123

  # Email settings:
  email_provider_username: user@example.com
  email_provider_password: changeme
  domain_name: gmail.com

  hellobi_iframe_url: https://docs.google.com/spreadsheets/d/1lS04vsZ21COJr3o0ritQl-OLve511n7EmjGPxOC_EsM/pubhtml?gid=0&amp;single=true&amp;widget=true&amp;headers=false

  secret_key_base: b990252a917b423fc5c445cf3335c9f72b45e07c64f18bb52ae0856d6e2489990355da7847ffced5cca812ef7ddbe7032d52df8f6477672697346a4753bc4f4a

test:
  # Admin user settings:
  admin_name: Admin
  admin_email: admin@admin.com
  admin_password: admin123

  # Email settings:
  email_provider_username: user@example.com
  email_provider_password: changeme
  domain_name: gmail.com

  hellobi_iframe_url: https://docs.google.com/spreadsheets/d/1lS04vsZ21COJr3o0ritQl-OLve511n7EmjGPxOC_EsM/pubhtml?gid=0&amp;single=true&amp;widget=true&amp;headers=false
  
  secret_key_base: 556dc8f23a0e70f1d4ee3e1f65fda52b1c0c11ccfbb70299a27a51cea7efc68dcc85fcf0d22bc7184b8428ce56dd86f0d9f719b820a447ccb5a2f3dc671e542d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  # Admin user settings:
  admin_name: Admin
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>

  # Email settings:
  email_provider_username: <%= ENV["EMAIL_PROVIDER_USERNAME"] %>
  email_provider_password: <%= ENV["EMAIL_PROVIDER_PASSWORD"] %>
  domain_name: gmail.com

  hellobi_iframe_url: <%= ENV["HELLOBI_IFRAME_URL"] %>

  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
